import MetaSearchAgent from '@/lib/search/metaSearchAgent';
import prompts from '../prompts';

export const searchHandlers: Record<string, MetaSearchAgent> = {
  webSearch: new MetaSearchAgent({
    activeEngines: [],
    queryGeneratorPrompt: prompts.webSearchRetrieverPrompt,
    responsePrompt: prompts.webSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    summarizer: true,
    maxSources: 10,
  }),
  academicSearch: new MetaSearchAgent({
    activeEngines: ['arxiv', 'google scholar', 'pubmed'],
    queryGeneratorPrompt: prompts.academicSearchRetrieverPrompt,
    responsePrompt: prompts.academicSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0,
    searchWeb: true,
    summarizer: false,
    maxSources: 20,
  }),
  financeNews: new MetaSearchAgent({
    activeEngines: ['google news', 'bing news', 'yahoo news', 'brave.news', 'google', 'bing', 'yahoo', 'duckduckgo', 'qwant news'],
    queryGeneratorPrompt: prompts.financeNewsRetrieverPrompt,
    responsePrompt: prompts.financeNewsResponsePrompt,
    rerank: true,
    rerankThreshold: 0.2,
    searchWeb: true,
    summarizer: true,
    maxSources: 25,
  }),
  financeFundamentals: new MetaSearchAgent({
    activeEngines: ['google', 'bing', 'brave', 'yahoo', 'duckduckgo'],
    queryGeneratorPrompt: prompts.financeFundamentalsRetrieverPrompt,
    responsePrompt: prompts.financeFundamentalsResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    summarizer: false,
    maxSources: 15,
  }),
  financeSocial: new MetaSearchAgent({
    activeEngines: ['reddit', 'youtube', 'google', 'bing', 'brave', 'duckduckgo', 'qwant news'],
    queryGeneratorPrompt: prompts.financeSocialRetrieverPrompt,
    responsePrompt: prompts.financeSocialResponsePrompt,
    rerank: true,
    rerankThreshold: 0.2,
    searchWeb: true,
    summarizer: false,
    maxSources: 20,
  }),
  writingAssistant: new MetaSearchAgent({
    activeEngines: [],
    queryGeneratorPrompt: '',
    responsePrompt: prompts.writingAssistantPrompt,
    rerank: true,
    rerankThreshold: 0,
    searchWeb: false,
    summarizer: false,
    maxSources: 5,
  }),
  wolframAlphaSearch: new MetaSearchAgent({
    activeEngines: ['wolframalpha'],
    queryGeneratorPrompt: prompts.wolframAlphaSearchRetrieverPrompt,
    responsePrompt: prompts.wolframAlphaSearchResponsePrompt,
    rerank: false,
    rerankThreshold: 0,
    searchWeb: true,
    summarizer: false,
    maxSources: 10,
  }),
  youtubeSearch: new MetaSearchAgent({
    activeEngines: ['youtube'],
    queryGeneratorPrompt: prompts.youtubeSearchRetrieverPrompt,
    responsePrompt: prompts.youtubeSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    summarizer: false,
    maxSources: 15,
  }),
  redditSearch: new MetaSearchAgent({
    activeEngines: ['reddit'],
    queryGeneratorPrompt: prompts.redditSearchRetrieverPrompt,
    responsePrompt: prompts.redditSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    summarizer: false,
    maxSources: 15,
  }),
};
